a, b = map(int,input().split())
a_list = list(map(int,input().split()))
b_list = list(map(int,input().split()))
len_a = set(a_list) - set(b_list)
len_b = set(b_list) - set(a_list)
print(len_a + len_b)